spring:
  kafka:
    bootstrap-servers: localhost:9191
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      pool-name: HikariPool-Auth
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  application:
    name: auth-service

  # FEIGN
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 2000      # timeout khi kết nối (ms)
      client:
        config:
          default:                    # áp dụng cho tất cả Feign client
            connectTimeout: 2000      # timeout khi connect
            readTimeout: 5000         # timeout khi đọc response
          profile-service:            # áp dụng riêng cho ProfileClient
            connectTimeout: 2000
            readTimeout: 5000


server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG


services:
  profile:
    url: http://localhost:8081



