spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_auth
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      pool-name: HikariPool-Auth
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  application:
    name: auth-service
server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
