spring:
  cloud:
    function:
      definition: profile-events-channel  # nhiều consumer độc lập
    stream:
      bindings:
        profile-events-channel-in-0:
          destination: profile-events-topic
          group: profile-event-group
          contentType: application/json

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: AUTO
        prefetch: 20
        concurrency: 2
        max-concurrency: 10
